/**
 * AI Review Service — Gathers forecast context and calls the local LLM gateway
 *
 * Builds structured text from all 6 data sources:
 * 1. Scenario metadata (periods, tax rate, sweep band)
 * 2. FC Review table data (entries by year)
 * 3. BS Modules (assets, liabilities with growth/yield/disposal)
 * 4. Income/Expense items
 * 5. FX assumptions
 * 6. Base year actuals
 *
 * Routes through the ocr-llm gateway (POST /task, task=finance_plan_review).
 * Local-only fallback chain: ollama_heavy:qwen3.6:35b → ollama_mid:qwen3:32b.
 * No public-cloud LLM in the path — financial detail stays on LAN/Tailnet.
 */

const db = require("../db");
const forecastRepo = require("../repositories").forecast;
// CR081 P0a — the CR050 reconcile a variant's sweep-band write needs; see `applyAction`.
const variants = require("./forecastVariants");
const psdataRepo = require("../repositories").psdata;

const DEFAULT_SYSTEM_PROMPT = `You are an experienced financial advisor reviewing a long-term retirement financial plan. The user's goal is to have sufficient funds so that they and their spouse can maintain a similar standard of living until they pass away, with minimal savings remaining at end of life.

Review the plan and provide structured feedback:

## Strong Points
What aspects of the plan are well-structured

## Concerns
Issues that could threaten the plan's viability

## Recommendations
Specific, actionable changes to improve the plan

## Key Risks
External risks the plan doesn't adequately address

## Questions
Clarifying questions you need answered to refine your advice

When you recommend specific numeric changes to the plan, include machine-readable action blocks so the user can auto-apply them. Format each as a JSON block on its own line, wrapped in triple backticks with the language tag "action":

\`\`\`action
{"type": "update_module", "module_id": 5, "field": "growth_rate", "proposed_value": 5, "reason": "Conservative growth assumption for retirement planning"}
\`\`\`

Supported action types and fields:
- update_module: growth_rate, tax_rate_override
- update_scenario: cash_sweep_low, cash_sweep_high

Give proposed_value and reason only. Do NOT state the current value: it is read from the plan itself and shown to the user before anything is applied. Only recommend a change to a module that appears in the data you were given.`;

const COMPARE_SYSTEM_PROMPT = `You are an experienced financial advisor. The user is comparing two long-term forecast scenarios for the same household: a BASELINE scenario (A) and a COMPARISON scenario (B). Both were generated by the same forecast engine from the data provided.

Explain where and why the scenarios differ. Structure your answer:

## Summary
The one-paragraph story of how B differs from A and what drives it.

## Key Differences
The specific inputs that differ (modules, income/expense items, assumptions) and the chain of effects each causes (e.g. higher salary → surplus swept to investments → more interest income → higher taxes).

## Trajectory
When the scenarios start to diverge, whether the gap widens or narrows, and any years where the advantage flips.

## Risks & Trade-offs
What each scenario is more exposed to; what the user gives up by choosing one over the other.

Ground every claim in the numbers provided — cite years and amounts. Do NOT include \`\`\`action blocks; this is analysis only, not plan editing.`;

/**
 * Gathers all forecast context for a scenario and formats as structured text
 */
async function buildForecastContext(scenarioName) {
  // 1. Scenario metadata
  const scenarioResult = await db.query(
    "SELECT * FROM forecast_scenarios WHERE name = $1",
    [scenarioName]
  );
  const scenario = scenarioResult.rows[0];
  if (!scenario) throw new Error(`Scenario "${scenarioName}" not found`);

  // Load assumptions
  const { loadScenarioConfig } = require("../../services/forecast/fcbuilder-setup");
  let config;
  try {
    config = await loadScenarioConfig(scenarioName);
  } catch (e) {
    config = null;
  }

  // 2. Modules with nested data
  const modules = await forecastRepo.findModulesByScenario(scenario.id);
  for (const mod of modules) {
    const [investments, disposals] = await Promise.all([
      db.query("SELECT * FROM forecast_module_investments WHERE module_id = $1 ORDER BY investment_date", [mod.id]),
      db.query("SELECT * FROM forecast_module_disposals WHERE module_id = $1 ORDER BY disposal_date", [mod.id]),
    ]);
    mod.investments = investments.rows;
    mod.disposals = disposals.rows;
  }


  // 4. Forecast entries (generated output) — aggregated per (year, account, module-tag)
  // We need both the raw flows AND a separate breakdown for BS year-end MV vs cash sweep
  const entriesResult = await db.query(`
    SELECT forecast_year, account, SUM(amount)::numeric as amount
    FROM forecast_entries
    WHERE scenario_id = $1
      AND COALESCE(module, '') NOT IN ('_cash_sweep', '_sweep_bal')
    GROUP BY forecast_year, account
    ORDER BY forecast_year, account
  `, [scenario.id]);

  // 4b. Cash sweep activity by year
  const sweepResult = await db.query(`
    SELECT forecast_year,
      SUM(CASE WHEN module = '_cash_sweep' AND account = 'Transfer - Bank' THEN amount ELSE 0 END)::numeric as sweep_to_bank
    FROM forecast_entries
    WHERE scenario_id = $1
    GROUP BY forecast_year
    ORDER BY forecast_year
  `, [scenario.id]);

  // 4c. BS module year-end MV (these account names match modules — engine writes year-end MV as the entry amount)
  const moduleNames = modules.map(m => m.name).filter(Boolean);
  const bsResult = moduleNames.length > 0
    ? await db.query(`
        SELECT forecast_year, account, SUM(amount)::numeric as mv
        FROM forecast_entries
        WHERE scenario_id = $1
          AND account = ANY($2::text[])
          AND COALESCE(module, '') NOT IN ('_cash_sweep', '_sweep_bal')
        GROUP BY forecast_year, account
        ORDER BY forecast_year, account
      `, [scenario.id, moduleNames])
    : { rows: [] };

  // 5. Base year values
  // CR069 P2 — one query over streams. Was three UNION branches across two tables, one of
  // which (`a.account_type = 'liability'`) silently returned 0 for every non-liability
  // module expense — the same hand-copied divergence CR049 removed from the engine's own
  // base-year query. The stream carries the amount and the direction carries the sign.
  const baseYearResult = await db.query(`
    SELECT
      COALESCE(line.name,
               CASE WHEN m.has_valuation THEN NULL ELSE COALESCE(acct.name, m.name) END) as fc_line,
      st.direction as type,
      SUM(CASE WHEN st.direction = 'income' THEN COALESCE(st.amount, 0)
                                            ELSE -COALESCE(st.amount, 0) END) as amount
    FROM forecast_streams st
    JOIN forecast_modules m ON m.id = st.module_id
    LEFT JOIN fc_lines line ON line.id = st.fc_line_id
    LEFT JOIN accounts acct ON acct.id = m.account_id
    WHERE m.scenario_id = $1 AND COALESCE(m.setup_status, 'new') NOT IN ('new', 'exclude')
    GROUP BY 1, 2
  `, [scenario.id]);

  // 6. App data (birth year etc)
  const appData = await psdataRepo.getAllAppData();
  const birthYear = appData?.birthYear || null;

  // Format as structured text
  const lines = [];

  lines.push("# FORECAST PLAN REVIEW DATA\n");

  // Scenario
  lines.push("## Scenario");
  lines.push(`Name: ${scenario.name}`);
  if (config?.scenario) {
    lines.push(`Period: ${config.scenario.PeriodStart} to ${config.scenario.PeriodEnd}`);
    lines.push(`Tax Rate: ${config.scenario.TaxRate}%`);
  }
  lines.push(`Cash Sweep Band: ${scenario.cash_sweep_low ?? 'not set'} (low) – ${scenario.cash_sweep_high ?? 'not set'} (high)`);
  if (birthYear) lines.push(`Birth Year: ${birthYear} (current age: ${new Date().getFullYear() - birthYear})`);
  lines.push("");

  // Modules
  lines.push("## Balance Sheet Modules");
  for (const mod of modules) {
    lines.push(`\n### ${mod.name} (ID: ${mod.id})`);
    lines.push(`  Account: ${mod.account_name || 'N/A'}, Type: ${mod.module_type || 'N/A'}, Currency: ${mod.currency}`);
    lines.push(`  Base Date: ${mod.base_date}, Cost Basis: ${fmt(mod.base_value)}, Market Value: ${fmt(mod.market_value)}`);
    lines.push(`  Cost Basis (USD): ${fmt(mod.base_value_usd)}, Market Value (USD): ${fmt(mod.market_value_usd)}`);
    lines.push(`  Growth Rate: ${mod.growth_rate}% (×inflation), Gains Tax Override: ${mod.tax_rate_override ?? 'default'}`);
    lines.push(`  Status: ${mod.setup_status}, Cash Sweep Target: ${mod.cash_sweep_target ? 'YES' : 'no'}`);
    // CR069 P3 — a module's income and expense are STREAMS. Printing the retired columns
    // would have told the model every module earns and spends nothing the moment anything was
    // saved through the new path, which is worse than omitting them.
    for (const st of mod.streams || []) {
      const bits = [
        `${st.direction} → ${st.fc_line_name || '(no line)'}`,
        `mode ${st.mode}`,
        st.mode === 'derived' ? 'amount derived from the loan balance' : `amount ${fmt(st.amount)}`,
      ];
      if (st.growth_mult != null) bits.push(`growth ×${st.growth_mult} inflation`);
      if (st.start_date || st.end_date) {
        bits.push(`window ${st.start_date ? new Date(st.start_date).getFullYear() : 'start'}–${st.end_date ? new Date(st.end_date).getFullYear() : 'end'}`);
      }
      if (st.tax_rate_override != null) bits.push(`income tax ${st.tax_rate_override}%`);
      lines.push(`  Stream: ${bits.join(', ')}`);
      for (const c of st.changes || []) {
        lines.push(`    ${new Date(c.change_date).getFullYear()}: ${c.flag} ${fmt(c.amount)}`);
      }
    }
    if (mod.disposals?.length) {
      lines.push(`  Disposals: ${mod.disposals.map(d => `${d.disposal_date} ${d.flag || ''} ${fmt(d.amount)}`).join(", ")}`);
    }
    if (mod.investments?.length) {
      lines.push(`  Investments: ${mod.investments.map(i => `${i.investment_date} ${fmt(i.amount)}`).join(", ")}`);
    }
  }
  lines.push("");

  // Income/Expense items
  lines.push("## Income & Expense Forecast Items");
  lines.push("");

  // FX Assumptions
  if (config?.scenario) {
    lines.push("## FX & Inflation Assumptions");
    const inf = config.inflationRates || [];
    const years = config.years || [];
    if (years.length > 0 && inf.length > 0) {
      lines.push(`  Inflation: ${inf[0]}% (applied from ${years[0]})`);
    }
    const plnRates = config.fxratesPLN || [];
    const eurRates = config.fxratesEUR || [];
    if (plnRates.length > 0) lines.push(`  PLN/USD: ${plnRates[0]}`);
    if (eurRates.length > 0) lines.push(`  EUR/USD: ${eurRates[0]}`);
    lines.push("");
  }

  // Base year budget
  lines.push("## Base Year Budget (annual P&L)");
  for (const row of baseYearResult.rows) {
    if (row.fc_line && row.amount) lines.push(`  ${row.fc_line}: ${fmt(row.amount)}`);
  }
  lines.push("");

  // Build per-year maps for the three output sections below
  const moduleNameSet = new Set(moduleNames);
  const flowMap = {};   // P&L flows by (year, account) — excludes cash sweep
  const bsMap = {};     // year-end MV per BS asset module
  const sweepMap = {};  // sweep transfer to bank per year

  for (const row of entriesResult.rows) {
    const yr = row.forecast_year;
    if (!flowMap[yr]) flowMap[yr] = {};
    flowMap[yr][row.account] = Number(row.amount);
  }
  for (const row of bsResult.rows) {
    const yr = row.forecast_year;
    if (!bsMap[yr]) bsMap[yr] = {};
    bsMap[yr][row.account] = Number(row.mv);
  }
  for (const row of sweepResult.rows) {
    sweepMap[row.forecast_year] = Number(row.sweep_to_bank);
  }
  const forecastYears = [...new Set([...Object.keys(flowMap), ...Object.keys(bsMap)])].sort();

  // Section A: P&L Flows by year (income, expenses, transfers — NOT balances)
  lines.push("## Annual P&L Flows by Year (USD)");
  lines.push("Net amount per category per year. POSITIVE = inflow / income; NEGATIVE = outflow / expense.");
  lines.push("Excludes cash sweep transfers (those are summarized separately below).");
  lines.push("`Bank Accounts` row here is the net cash flow change for that year — it is NOT the year-end bank balance.");
  if (forecastYears.length > 0) {
    lines.push(`\nYears: ${forecastYears.join(", ")}\n`);
    const flowAccounts = new Set();
    for (const yr of forecastYears) for (const acc of Object.keys(flowMap[yr] || {})) {
      // Exclude BS module accounts from this section — they go in the BS section below
      if (!moduleNameSet.has(acc)) flowAccounts.add(acc);
    }
    for (const acc of [...flowAccounts].sort()) {
      const vals = forecastYears.map(yr => fmt(flowMap[yr]?.[acc] || 0));
      lines.push(`${acc}: ${vals.join(" | ")}`);
    }
  }
  lines.push("");

  // Section B: Balance Sheet — year-end Market Value of asset modules
  lines.push("## Balance Sheet — Year-End Market Value by Module (USD)");
  lines.push("Year-end MV per asset module, after all flows for the year (growth, yield, invest/dispose).");
  if (forecastYears.length > 0 && Object.keys(bsMap).length > 0) {
    lines.push(`\nYears: ${forecastYears.join(", ")}\n`);
    const bsAccounts = new Set();
    for (const yr of forecastYears) for (const acc of Object.keys(bsMap[yr] || {})) bsAccounts.add(acc);
    for (const acc of [...bsAccounts].sort()) {
      const vals = forecastYears.map(yr => fmt(bsMap[yr]?.[acc] || 0));
      lines.push(`${acc}: ${vals.join(" | ")}`);
    }
  }
  lines.push("");

  // Section C: Cash Sweep activity + Bank Accounts running balance
  lines.push("## Cash Account & Cash Sweep Activity");
  const lowBand = scenario.cash_sweep_low;
  const highBand = scenario.cash_sweep_high;
  if (lowBand != null || highBand != null) {
    lines.push(`Cash sweep band: low=${fmt(lowBand)}, high=${fmt(highBand)} (USD).`);
    lines.push(`The engine maintains Bank Accounts within this band by transferring to/from the cash sweep target module.`);
    lines.push(`A NEGATIVE annual P&L Bank Accounts flow is offset by a POSITIVE sweep transfer (and vice versa) so the displayed bank balance stays inside the band.`);
  }
  if (forecastYears.length > 0 && Object.keys(sweepMap).length > 0) {
    lines.push("\nNet sweep transfer TO Bank Accounts per year (positive = sweep brought cash in to cover deficit; negative = excess swept out to module):");
    const sweepLine = forecastYears.map(yr => fmt(sweepMap[yr] || 0));
    lines.push(`Sweep → Bank: ${sweepLine.join(" | ")}`);
    lines.push("\nNet annual change to Bank Accounts (P&L flow + sweep) — non-zero values reveal years where the bank balance materially shifted:");
    const netLine = forecastYears.map(yr => {
      const bankFlow = (flowMap[yr]?.["Bank Accounts"] || 0);
      const sweep = (sweepMap[yr] || 0);
      return fmt(bankFlow + sweep);
    });
    lines.push(`Net Bank Δ: ${netLine.join(" | ")}`);
  }
  lines.push("");

  return { context: lines.join("\n"), scenario, modules };
}

/**
 * Builds a two-scenario comparison context: a precomputed top-divergence
 * table (cumulative B − A per account over the engine output) followed by
 * both scenarios' full single-scenario contexts. (CR040 P3)
 */
async function buildCompareContext(scenarioNameA, scenarioNameB) {
  const [a, b] = [
    await buildForecastContext(scenarioNameA),
    await buildForecastContext(scenarioNameB),
  ];

  // Cumulative engine output per account for each scenario (sweep tags excluded,
  // same filter as the per-scenario context) — joined into B − A deltas.
  const cumRows = async (scenarioId) => {
    const r = await db.query(`
      SELECT account, SUM(amount)::numeric AS total
      FROM forecast_entries
      WHERE scenario_id = $1
        AND COALESCE(module, '') NOT IN ('_cash_sweep', '_sweep_bal')
      GROUP BY account
    `, [scenarioId]);
    return new Map(r.rows.map((row) => [row.account, Number(row.total)]));
  };
  const [totalsA, totalsB] = [await cumRows(a.scenario.id), await cumRows(b.scenario.id)];

  const accounts = new Set([...totalsA.keys(), ...totalsB.keys()]);
  const divergences = [...accounts]
    .map((acc) => ({
      account: acc,
      a: totalsA.get(acc) ?? null,
      b: totalsB.get(acc) ?? null,
      delta: (totalsB.get(acc) ?? 0) - (totalsA.get(acc) ?? 0),
    }))
    .filter((d) => Math.abs(d.delta) > 0.5)
    .sort((x, y) => Math.abs(y.delta) - Math.abs(x.delta))
    .slice(0, 15);

  const lines = [];
  lines.push("# SCENARIO COMPARISON DATA\n");
  lines.push(`Baseline scenario (A): ${scenarioNameA}`);
  lines.push(`Comparison scenario (B): ${scenarioNameB}`);
  lines.push("All deltas below read B − A.\n");

  lines.push("## Top Divergences (cumulative engine output per account, USD)");
  if (divergences.length === 0) {
    lines.push("The scenarios' engine outputs are identical — no account diverges.");
  } else {
    lines.push("account: A cumulative | B cumulative | delta (B − A)");
    for (const d of divergences) {
      lines.push(`${d.account}: ${fmt(d.a)} | ${fmt(d.b)} | ${fmt(d.delta)}`);
    }
  }
  lines.push("");

  lines.push(`\n# BASELINE SCENARIO A: ${scenarioNameA}\n`);
  lines.push(a.context);
  lines.push(`\n# COMPARISON SCENARIO B: ${scenarioNameB}\n`);
  lines.push(b.context);

  return { context: lines.join("\n"), scenarioA: a.scenario, scenarioB: b.scenario };
}

function fmt(v) {
  const n = Number(v);
  if (!Number.isFinite(n)) return "—";
  return n.toLocaleString("en-US", { maximumFractionDigits: 0 });
}

/**
 * Calls the local LLM gateway with the forecast context and conversation history.
 * The /task endpoint is single-turn, so we flatten multi-turn history into a
 * User:/Assistant: transcript and end with an "Assistant:" cue.
 */
async function callGateway({ systemPrompt, messages, forecastContext }) {
  const gatewayUrl = process.env.LLM_GATEWAY_URL || "http://192.168.1.61:8080";

  const lines = ["--- FORECAST DATA ---", forecastContext, "", "--- CONVERSATION ---"];
  for (const m of messages) {
    const speaker = m.role === "user" ? "User" : "Assistant";
    lines.push(`${speaker}: ${m.content}`);
    lines.push("");
  }
  lines.push("Assistant:");
  const prompt = lines.join("\n");

  const response = await fetch(`${gatewayUrl}/task`, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({
      task: "finance_plan_review",
      prompt,
      system: systemPrompt,
      max_tokens: 4096,
    }),
    signal: AbortSignal.timeout(300_000),
  });

  if (!response.ok) {
    const errText = await response.text().catch(() => "");
    throw new Error(`LLM gateway ${response.status}: ${errText.slice(0, 500)}`);
  }

  const data = await response.json();
  const content = data.response || "";

  const actions = [];
  const actionRegex = /```action\s*\n([\s\S]*?)\n```/g;
  let match;
  while ((match = actionRegex.exec(content)) !== null) {
    try {
      actions.push(JSON.parse(match[1].trim()));
    } catch (e) { /* skip malformed actions */ }
  }

  return { content, actions: actions.length > 0 ? actions : null };
}

/**
 * Creates a new AI review session for a scenario
 */
// Treat a review as stuck if it's been pending longer than this (matches the
// gateway-call AbortSignal of 5min, plus a small buffer).
const STALE_PENDING_MS = 6 * 60 * 1000;

/**
 * Background worker — runs the gateway call and writes results to the DB.
 * Never thrown; failures are persisted as status='failed'.
 */
async function processReview(reviewId) {
  try {
    // Derive scenario names from the review row so follow-ups rebuild the
    // right context (including the compare pair) without callers passing it.
    const reviewRow = await db.query(
      `SELECT r.id, s.name AS scenario_name, cs.name AS compare_name
         FROM fc_ai_reviews r
         JOIN forecast_scenarios s ON r.scenario_id = s.id
         LEFT JOIN forecast_scenarios cs ON r.compare_scenario_id = cs.id
        WHERE r.id = $1`,
      [reviewId]
    );
    if (reviewRow.rows.length === 0) throw new Error("Review not found");
    const { scenario_name: scenarioName, compare_name: compareName } = reviewRow.rows[0];

    let systemPrompt;
    let context;
    if (compareName) {
      // Compare reviews use the fixed compare prompt (the ai_review_prompt
      // app-data override applies to single-scenario reviews only).
      systemPrompt = COMPARE_SYSTEM_PROMPT;
      ({ context } = await buildCompareContext(scenarioName, compareName));
    } else {
      const customPrompt = await psdataRepo.getAppData("ai_review_prompt");
      systemPrompt = (typeof customPrompt === "string" && customPrompt.trim())
        ? customPrompt : DEFAULT_SYSTEM_PROMPT;
      ({ context } = await buildForecastContext(scenarioName));
    }

    const messagesResult = await db.query(
      "SELECT role, content FROM fc_ai_messages WHERE review_id = $1 ORDER BY created_at",
      [reviewId]
    );
    const messages = messagesResult.rows;

    const { content, actions } = await callGateway({
      systemPrompt,
      messages,
      forecastContext: context,
    });

    await db.query(
      "INSERT INTO fc_ai_messages (review_id, role, content, actions) VALUES ($1, 'assistant', $2, $3)",
      [reviewId, content, actions ? JSON.stringify(actions) : null]
    );
    await db.query(
      "UPDATE fc_ai_reviews SET status = 'completed', error_message = NULL, updated_at = NOW() WHERE id = $1",
      [reviewId]
    );
  } catch (err) {
    console.error(`[ai-review] background worker failed for review ${reviewId}:`, err.message);
    await db.query(
      "UPDATE fc_ai_reviews SET status = 'failed', error_message = $2, updated_at = NOW() WHERE id = $1",
      [reviewId, String(err.message || err).slice(0, 1000)]
    ).catch(() => {});
  }
}

/**
 * Creates a new review record + initial user message and fires the gateway
 * call in the background. Returns immediately with status='pending'.
 */
async function createReview(scenarioName, compareWith = null) {
  const scenarioResult = await db.query(
    "SELECT id FROM forecast_scenarios WHERE name = $1",
    [scenarioName]
  );
  if (scenarioResult.rows.length === 0) throw new Error(`Scenario "${scenarioName}" not found`);
  const scenarioId = scenarioResult.rows[0].id;

  let compareScenarioId = null;
  if (compareWith) {
    if (compareWith === scenarioName) throw new Error("Compare scenario must differ from the baseline");
    const compareResult = await db.query(
      "SELECT id FROM forecast_scenarios WHERE name = $1",
      [compareWith]
    );
    if (compareResult.rows.length === 0) throw new Error(`Scenario "${compareWith}" not found`);
    compareScenarioId = compareResult.rows[0].id;
  }

  const title = compareWith
    ? `Compare: ${scenarioName} vs ${compareWith}`
    : `Review of ${scenarioName}`;
  const reviewResult = await db.query(
    "INSERT INTO fc_ai_reviews (scenario_id, compare_scenario_id, title, status) VALUES ($1, $2, $3, 'pending') RETURNING *",
    [scenarioId, compareScenarioId, title]
  );
  const review = reviewResult.rows[0];

  const userMessage = compareWith
    ? "Please compare these two forecast scenarios and explain where and why they differ."
    : "Please review my financial plan and provide your analysis.";
  await db.query(
    "INSERT INTO fc_ai_messages (review_id, role, content) VALUES ($1, 'user', $2)",
    [review.id, userMessage]
  );

  // Fire-and-forget; the worker writes results to the DB. Polled via /:id/status.
  processReview(review.id);

  return { review };
}

/**
 * Inserts the user's follow-up, marks the review pending, and fires the
 * gateway call in the background. Returns immediately.
 */
async function sendMessage(reviewId, userMessage) {
  const reviewResult = await db.query(
    "SELECT id, status FROM fc_ai_reviews WHERE id = $1",
    [reviewId]
  );
  const review = reviewResult.rows[0];
  if (!review) throw new Error("Review not found");
  if (review.status === "pending") throw new Error("A review is already in progress for this conversation");

  await db.query(
    "INSERT INTO fc_ai_messages (review_id, role, content) VALUES ($1, 'user', $2)",
    [reviewId, userMessage]
  );
  await db.query(
    "UPDATE fc_ai_reviews SET status = 'pending', error_message = NULL, updated_at = NOW() WHERE id = $1",
    [reviewId]
  );

  processReview(reviewId);

  return { reviewId, status: "pending" };
}

/**
 * Returns the current status of a review. Marks stale-pending reviews
 * (older than STALE_PENDING_MS) as failed before returning.
 */
async function getReviewStatus(reviewId) {
  await db.query(
    `UPDATE fc_ai_reviews
       SET status = 'failed',
           error_message = COALESCE(error_message, 'Review timed out — server may have restarted while running.'),
           updated_at = NOW()
     WHERE id = $1
       AND status = 'pending'
       AND updated_at < NOW() - INTERVAL '${Math.floor(STALE_PENDING_MS / 1000)} seconds'`,
    [reviewId]
  );

  const result = await db.query(
    `SELECT r.id, r.status, r.error_message, r.updated_at,
            (SELECT COUNT(*)::int FROM fc_ai_messages WHERE review_id = r.id) AS message_count
       FROM fc_ai_reviews r WHERE r.id = $1`,
    [reviewId]
  );
  if (result.rows.length === 0) throw new Error("Review not found");
  return result.rows[0];
}

// CR081 P0a — the fields an LLM-authored action may write, and nothing else.
const ALLOWED_MODULE_FIELDS = ["growth_rate", "tax_rate_override"];
const ALLOWED_SCENARIO_FIELDS = ["cash_sweep_low", "cash_sweep_high"];

/**
 * Validate an action against the review it came from, and read its CURRENT value from the DATABASE.
 *
 * Split out of `applyAction` (CR081 P0a) so the confirm dialog and the write share one validator.
 * Two callers deriving the same rules separately is how the front end came to advertise an
 * `incexp_id` action the server refuses outright.
 *
 * ⚠️ The `reviewId` argument is the point of this function. `/apply` used to take the action ALONE,
 * so the write target came from the model's JSON and nothing checked it belonged to the scenario
 * under review — a review of `2026 Downside` could write a module in `2026 Base`, whose edits then
 * fan out to four variants, with the dialog never naming a scenario. Found by the CR081 technical
 * review, 2026-08-11.
 *
 * `current_value` is read HERE, from the row, never taken from the action. The model is asked to
 * supply one in its JSON and the dialog used to render it — so a hallucinated "from" value meant
 * the owner approved a change against a state that was never true. That is CR077 §4's rule
 * (*nothing generated may state a number*) broken on the one surface where a number is acted on
 * rather than read.
 *
 * @returns {Object} { type, entity, id, field, currentValue, proposedValue, name, scenarioId,
 *                     scenarioName, isVariant }
 */
async function resolveAction(reviewId, action) {
  if (!action || typeof action !== "object") throw new Error("Action is required");
  const { type, field, proposed_value } = action;

  if (reviewId == null || Number.isNaN(Number(reviewId))) {
    throw new Error(
      "This recommendation predates the scenario check and cannot be applied. Re-run the review — " +
      "an action with no review behind it has no scenario to be checked against."
    );
  }

  const reviewRes = await db.query(
    "SELECT id, scenario_id, compare_scenario_id FROM fc_ai_reviews WHERE id = $1",
    [Number(reviewId)]
  );
  if (reviewRes.rows.length === 0) throw new Error("Review not found");
  const review = reviewRes.rows[0];

  // A compare review legitimately discusses BOTH sides, so both are in scope — and nothing else is.
  const inScope = [review.scenario_id, review.compare_scenario_id]
    .filter((v) => v != null)
    .map(Number);

  const scenarioName = async (id) => (await forecastRepo.findScenarioById(id))?.name ?? `#${id}`;

  if (type === "update_module") {
    if (!ALLOWED_MODULE_FIELDS.includes(field)) {
      throw new Error(`Field "${field}" not allowed for auto-apply`);
    }
    const target = await forecastRepo.findModuleById(action.module_id);
    if (!target) throw new Error("Module not found");

    if (!inScope.includes(Number(target.scenario_id))) {
      throw new Error(
        `"${target.name}" belongs to "${await scenarioName(target.scenario_id)}", which this review ` +
        `is not about. Refusing: an edit applied to the wrong scenario can also fan out to its ` +
        `variants, and nothing on this screen would have said so.`
      );
    }

    // CR070 P0 (D5) — refuse to write a field the module's own FORM would not show.
    //
    // Both allowed fields belong to the valuation: `growth_rate` is compounded only when
    // `has_valuation` is true (the engine reads `hasValuation ? Growth : 0`), and
    // `tax_rate_override` is the rate on a realized capital gain. On a flow module neither is
    // read — so applying one here would store a number that changes nothing, in a field the
    // editor does not render for that module, arrived at by one click on an LLM's suggestion.
    // That is the exact hazard CR062's `isLoanModule` comment describes, on the one path where
    // the value is not typed by the owner at all.
    //
    // Keyed on `has_valuation`, an ENGINE branch — not on `module_type`, which is free text.
    if (target.has_valuation === false) {
      throw new Error(
        `"${field}" belongs to a module's valuation, and "${target.name}" has none — it is a ` +
        `flow module, so the engine would never read the value. Refusing rather than storing a ` +
        `number that changes nothing and cannot be seen.`
      );
    }

    const scenario = await forecastRepo.findScenarioById(target.scenario_id);
    return {
      type, entity: "module", id: Number(target.id), field,
      currentValue: target[field] ?? null,
      proposedValue: proposed_value,
      name: target.name,
      scenarioId: Number(target.scenario_id),
      scenarioName: scenario?.name ?? null,
      isVariant: scenario?.parent_scenario_id != null,
    };
  }

  if (type === "update_incexp") {
    // CR069 P2 — refused rather than silently applied to a table nothing reads.
    throw new Error(
      'Income/expense items are now modules with streams (CR069 P2) — this recommendation ' +
      'cannot be auto-applied. Edit the module on the Forecast Modules page.'
    );
  }

  if (type === "update_scenario") {
    if (!ALLOWED_SCENARIO_FIELDS.includes(field)) {
      throw new Error(`Field "${field}" not allowed for auto-apply`);
    }
    const id = Number(action.scenario_id);
    if (!inScope.includes(id)) {
      throw new Error(
        `Scenario "${await scenarioName(id)}" is not the one this review is about. Refusing.`
      );
    }
    const scenario = await forecastRepo.findScenarioById(id);
    if (!scenario) throw new Error("Scenario not found");
    return {
      type, entity: "scenario", id, field,
      currentValue: scenario[field] ?? null,
      proposedValue: proposed_value,
      name: scenario.name,
      scenarioId: id,
      scenarioName: scenario.name,
      isVariant: scenario.parent_scenario_id != null,
    };
  }

  throw new Error(`Unknown action type: ${type}`);
}

/**
 * Applies a recommended action (Phase 1: numeric field updates only).
 *
 * Validated by `resolveAction`, which owns every refusal and reads the pre-write value from the
 * row. This function only writes, reconciles and records.
 */
async function applyAction(reviewId, action) {
  const resolved = await resolveAction(reviewId, action);
  const { entity, id, field, currentValue, proposedValue } = resolved;

  if (entity === "module") {
    // `updateModule` intercepts a variant write and records it as a CR050 override — which is why
    // the module path is variant-safe at all, and why `update_scenario` below needs its own step.
    const updated = await forecastRepo.updateModule(id, { [field]: proposedValue });
    if (!updated) throw new Error("Module not found");
  } else {
    const updated = await forecastRepo.updateScenario(id, { [field]: proposedValue });
    if (!updated) throw new Error("Scenario not found");

    // ⚠️ CR081 P0a — the CR050 reconcile lives in the scenarios ROUTE, not the repository, so this
    // path bypassed it entirely: a sweep-band change applied to a variant reported success and was
    // then erased by the next sync rewriting the band from base ⊕ overrides. Accepted, stored,
    // silently reverted — the shape the route's own comment calls "the one failure mode this
    // feature must not have". Found by the CR081 technical review, 2026-08-11.
    if (resolved.isVariant) {
      await variants.reconcileAssumptionOverrides(id);
    }
  }

  // An AI-originated write left no trace of any kind before this: `audit_log` has existed since
  // migration 001 and nothing in the codebase had ever written to it. One row is cheap, and this
  // is the one path where the value was not typed by the owner.
  await db.query(
    `INSERT INTO audit_log (table_name, record_id, action, old_values, new_values, user_info)
     VALUES ($1, $2, 'ai_review_apply', $3, $4, $5)`,
    [
      entity === "module" ? "forecast_modules" : "forecast_scenarios",
      id,
      JSON.stringify({ [field]: currentValue }),
      JSON.stringify({ [field]: proposedValue }),
      `ai-review:${reviewId}`,
    ]
  );

  return {
    success: true,
    entity,
    id,
    field,
    value: proposedValue,
    // The value that was actually there, so the UI can report the change it really made rather
    // than the one the model claimed it was making.
    previous_value: currentValue,
    scenario: resolved.scenarioName,
    is_variant: resolved.isVariant,
  };
}

module.exports = {
  createReview,
  sendMessage,
  getReviewStatus,
  applyAction,
  resolveAction,   // CR081 P0a — the shared validator, also the confirm dialog's source of truth
  buildCompareContext,
  DEFAULT_SYSTEM_PROMPT,
  COMPARE_SYSTEM_PROMPT,
};
