-- 044 — rewrite bank-feed account ids from Sheet UUIDs to fintable API ids (CR059 P3a)
--
-- GENERATED by bank-feed scripts/emit-crosswalk-sql.js from a verified crosswalk
-- plan (scripts/crosswalk-plan.js). Do not hand-edit the pairs: regenerate.
--
-- Plan generated: 2026-08-01T16:44:07.079Z
-- Pairs: 31  (SINGLE=17, CONFIRMED=14)
--
-- WHAT THIS IS. fintable's API identifies accounts differently from the Google
-- Sheet we have been ingesting: we store the Sheet's account UUIDs, the API
-- serves its own ids. Swapping upstreams without this rewrite orphans every
-- mapping at once — each fed account silently unmapped, taking its feed_sign,
-- feed_negate_tx and promote_from_date with it (CR059 §4).
--
-- HOW THE PAIRS WERE ESTABLISHED. Two signals computed INDEPENDENTLY, not as a
-- fallback chain: the API account id embedded in our own composite transaction
-- ids, and name+currency. Where both fire they must agree; disagreement produces
-- a refusal rather than a mapping. The plan was verified to be a complete
-- bijection (31 distinct Sheet ids to 31 distinct API ids, no unclaimed API
-- account) and identical across repeated runs before this file was generated.
--
-- NOT TOUCHED, deliberately: transactions.bank_feed_external_id. CR059 §4 called
-- it "the site that bites" and required rewriting it in this same transaction —
-- correct at the time, when the plan re-ingested full history. Pass-2 M1 removed
-- the need by setting the ingest floor at the cutover: rows before it are never
-- fetched, and rows inside the overlap window keep the ids we already hold (the
-- bank-feed boundary carry-over). So the ledger's only duplicate guard keeps
-- matching, and this migration never writes to the ledger.
--
-- Idempotent: re-running finds no Sheet-format ids left and updates 0 rows. The
-- post-conditions are written to hold after either the first or a second run.

BEGIN;

CREATE TEMP TABLE crosswalk (sheet_id text PRIMARY KEY, api_id text NOT NULL UNIQUE) ON COMMIT DROP;
INSERT INTO crosswalk (sheet_id, api_id) VALUES
    ('OeaD883LY8HbBELgMLNVHZMpkbEPyaHp0opdV', '7991192043957361829'),  -- 360 Performance Savings (5537) (USD), SINGLE via name+currency
    ('j5a1n7R1OmtJ0zekLmMpCg7evP4DrJikqzVpL6', '7814887570436791159'),  -- Black Card (9915) (USD), SINGLE via name+currency
    ('e5a23070-13bb-49af-8f2d-e552e159b570', '8829675791129122371'),  -- Cash Management (USD), SINGLE via name+currency
    ('369564674', '6266063543561075600'),  -- CHASE SAVINGS (USD), CONFIRMED via both
    ('247bc196-4ac8-4bc2-a5ca-69c693a475d3', '4184944067129866862'),  -- Christopher Biedermann (EUR) (2211) (EUR), CONFIRMED via both
    ('d736e5e2-9f13-44da-a96e-b66ad735b8a3', 'acc_01KYS5BECVFH89QPSRQSFN4M99'),  -- Christopher Biedermann (EUR) (8325) (EUR), SINGLE via name+currency
    ('185c3704-14ab-4f1a-8ed0-bd040ce37b85', '3020755806482258456'),  -- Christopher Biedermann (PLN) (5413) (PLN), SINGLE via name+currency
    ('f4f38f9a-199c-4b32-b9f8-074dd0c3febd', 'acc_01KYS5BHZE7F9CJYZHJWXC04ZT'),  -- Christopher Biedermann (PLN) (8325) (PLN), SINGLE via name+currency
    ('06c5dab0-7e8c-40fc-80eb-e2f94dd13ae0', '6521708934254164984'),  -- Christopher Biedermann (USD) (1446) (USD), CONFIRMED via both
    ('4de06156-3a5c-4a12-8701-e28a5ff18d2f', '4044604745776048193'),  -- Christopher Biedermann (USD) (8325) (USD), SINGLE via name+currency
    ('69b7d3c5-fd86-4b6c-929d-073a5ed97704', '9118349300383451158'),  -- CHRISTOPHER F BIEDERMANN (PLN) (1791) (PLN), CONFIRMED via both
    ('1cf189ea-1fc3-44ff-b030-d85093f2825c', '7629175587326935916'),  -- CHRISTOPHER FRANZ BIEDERMANN (EUR) (9421) (EUR), CONFIRMED via both
    ('R1ZQnw7QNqHBJqAxKXEvsZM9pa86e9H99JZv4', '2125222118205134100'),  -- Delta SkyMiles® Reserve Card (1002) (USD), SINGLE via name+currency
    ('e420ad75-9a54-4c3b-b98a-5adbd8b6061e', '238417359251307816'),  -- Fixed Income (USD), SINGLE via name+currency
    ('nEn1jK51zbT4Zq5vA1dPs8E6XomJO6FjjOkdq', '4845293972953545556'),  -- Hilton Honors Aspire Card (1007) (USD), SINGLE via name+currency
    ('190d7bf1-c77d-43bc-9061-b7646669b176', '3434139509958219125'),  -- Individual (USD), SINGLE via name+currency
    ('0331dfa6-706c-415c-aba6-efb81f6fb86d', '3062089709092272539'),  -- Infinity CB (PLN), CONFIRMED via both
    ('ebc00ada-6ee2-43fe-9ed3-df2bf77ecc6c', '306283222131625591'),  -- Infinity KB (PLN), CONFIRMED via both
    ('QD8EXdyENPIqkb5od87AtPYrpvRQOrU993xZw', '2779036839116781874'),  -- Marriott Bonvoy Brilliant® American Express® Card (4003) (USD), SINGLE via name+currency
    ('385966008', '6802282097996095156'),  -- Marriott Chase (USD), CONFIRMED via both
    ('466a4ae8-b682-4256-96aa-e0bcc80de3fb', '4351213228517462827'),  -- OC MEDYCYNY ESTETYCZNEJ (PLN) (8781) (PLN), CONFIRMED via both
    ('3bd9f941-8d06-4302-8950-35b532cebbaa', '1023381748687979037'),  -- Options (USD), SINGLE via name+currency
    ('b235e3d8-34fb-4678-97da-bc03c6f01576', '5739453956153598534'),  -- PKO EUR (EUR), SINGLE via name+currency
    ('6fbf7e12-e099-4d39-ac12-fbf26d81e77d', '2668543056229379631'),  -- PKO Main (PLN), CONFIRMED via both
    ('b2416778-a3a1-44d9-bd34-b62862e97b5b', '5402597747075704143'),  -- PKO OCME (PLN), CONFIRMED via both
    ('012a5d7f-19de-45ee-a451-dfa2481bca47', '193084888964906269'),  -- PKO USD (USD), SINGLE via name+currency
    ('280752349', '4967708320908493007'),  -- Prime Visa (USD), CONFIRMED via both
    ('5216d738-82a9-4956-9b23-aff70d07c827', '8834888811902688614'),  -- Rollover IRA (USD), SINGLE via name+currency
    ('d0bbc717-0e20-4b46-9e50-eb5d323849cc', '6050344781753535419'),  -- SAVINGS (PLN) (2790) (PLN), CONFIRMED via both
    ('4edb12ab-749d-4e1f-bbe4-5d31aaee30d8', '2836626511221389035'),  -- Stocks (USD), SINGLE via name+currency
    ('4741523', '7537429121392136946')  -- TOTAL CHECKING (USD), CONFIRMED via both
;

-- Preconditions. Each of these would silently corrupt the mapping if ignored, so
-- they abort before anything is written rather than being checked afterwards.
DO $$
DECLARE collide INT; uncovered INT;
BEGIN
  -- An API id that ALREADY exists as a mapping means this has been partly applied
  -- or the plan is stale; rewriting onto it would merge two accounts.
  SELECT COUNT(*) INTO collide
    FROM crosswalk c
    JOIN account_source_mappings m ON m.external_name = c.api_id AND m.source = 'bank-feed'
   WHERE EXISTS (SELECT 1 FROM account_source_mappings o WHERE o.source='bank-feed' AND o.external_name = c.sheet_id);
  IF collide > 0 THEN
    RAISE EXCEPTION 'migration 044: % API id(s) already exist as a bank-feed mapping', collide;
  END IF;

  -- A mapping this plan does not cover would be left pointing at a Sheet id that
  -- the feed will never send again — silently unmapped, which is the exact
  -- failure this migration exists to prevent.
  SELECT COUNT(*) INTO uncovered
    FROM account_source_mappings m
   WHERE m.source = 'bank-feed'
     AND m.external_name NOT IN (SELECT sheet_id FROM crosswalk)
     AND m.external_name NOT IN (SELECT api_id FROM crosswalk);
  IF uncovered > 0 THEN
    RAISE EXCEPTION 'migration 044: % bank-feed mapping(s) not covered by the plan', uncovered;
  END IF;
END $$;

-- Site 1 — the mappings. This carries feed_sign, feed_negate_tx and
-- promote_from_date across with it, because the row is updated rather than
-- replaced. Includes ignore-only rows: an ignore decision must survive the
-- cutover too, or an account deliberately excluded quietly returns.
UPDATE account_source_mappings m
   SET external_name = c.api_id
  FROM crosswalk c
 WHERE m.source = 'bank-feed' AND m.external_name = c.sheet_id;

-- Site 2 — staged rows, so the recon page and the promote path keep joining
-- staging to its mapping. Historical staging rows are rewritten too: leaving them
-- on the old id would strand them from the mapping that governs their promotion.
UPDATE bankfeed_staging s
   SET feed_account_external_id = c.api_id
  FROM crosswalk c
 WHERE s.feed_account_external_id = c.sheet_id;

-- Post-conditions. The third is the one that matters: counting rows updated only
-- proves the UPDATE ran, whereas an orphaned staging row proves it was wrong.
DO $$
DECLARE leftover_map INT; leftover_stage INT; orphan INT; dupes INT;
BEGIN
  SELECT COUNT(*) INTO leftover_map
    FROM account_source_mappings m JOIN crosswalk c ON c.sheet_id = m.external_name
   WHERE m.source = 'bank-feed';
  IF leftover_map > 0 THEN
    RAISE EXCEPTION 'migration 044: % mapping(s) still carry a Sheet id', leftover_map;
  END IF;

  SELECT COUNT(*) INTO leftover_stage
    FROM bankfeed_staging s JOIN crosswalk c ON c.sheet_id = s.feed_account_external_id;
  IF leftover_stage > 0 THEN
    RAISE EXCEPTION 'migration 044: % staging row(s) still carry a Sheet id', leftover_stage;
  END IF;

  -- Every staged row must still resolve to a mapping. This is the check that
  -- would catch a half-applied rewrite, which no count comparison can.
  SELECT COUNT(*) INTO orphan
    FROM bankfeed_staging s
   WHERE NOT EXISTS (
     SELECT 1 FROM account_source_mappings m
      WHERE m.source = 'bank-feed' AND m.external_name = s.feed_account_external_id);
  IF orphan > 0 THEN
    RAISE EXCEPTION 'migration 044: % staged row(s) no longer resolve to a mapping', orphan;
  END IF;

  SELECT COUNT(*) INTO dupes FROM (
    SELECT external_name FROM account_source_mappings
     WHERE source = 'bank-feed' GROUP BY external_name HAVING COUNT(*) > 1) d;
  IF dupes > 0 THEN
    RAISE EXCEPTION 'migration 044: % duplicate bank-feed external_name(s) — two accounts merged', dupes;
  END IF;
END $$;

COMMIT;
