-- 051 — roll back 044: put bank-feed account ids back on the Sheet UUIDs (CR059)
--
-- GENERATED by bank-feed scripts/emit-crosswalk-sql.js from a verified crosswalk
-- plan (scripts/crosswalk-plan.js). Do not hand-edit the pairs: regenerate.
--
-- Plan generated: 2026-08-01T16:44:07.079Z
-- Pairs: 31  (SINGLE=17, CONFIRMED=14)
--
-- WHAT THIS IS. fintable's API identifies accounts differently from the Google
-- Sheet we have been ingesting: we store the Sheet's account UUIDs, the API
-- serves its own ids. Swapping upstreams without this rewrite orphans every
-- mapping at once — each fed account silently unmapped, taking its feed_sign,
-- feed_negate_tx and promote_from_date with it (CR059 §4).
--
-- HOW THE PAIRS WERE ESTABLISHED. Two signals computed INDEPENDENTLY, not as a
-- fallback chain: the API account id embedded in our own composite transaction
-- ids, and name+currency. Where both fire they must agree; disagreement produces
-- a refusal rather than a mapping. The plan was verified to be a complete
-- bijection (31 distinct Sheet ids to 31 distinct API ids, no unclaimed API
-- account) and identical across repeated runs before this file was generated.
--
-- WHY. 044 was applied to prod at 2026-08-01 18:53:04 before it was ready, and it
-- is INCOMPLETE: fin keys feed accounts in THREE places and 044 rewrites two.
-- bankfeed_balances.feed_account_external_id was in neither the migration nor
-- CR059 §4's identifier inventory, so after 044 the reconcile page could not join
-- a single account to its feed balance and every mapped account read "no feed".
--
-- The feed did not corrupt anything, it STALLED: rows kept arriving from the Sheet
-- under Sheet ids, matched no mapping, and therefore did not promote. Measured
-- before this rollback: 255 staged rows unmapped, 90 unpromoted, and **0 rows
-- promoted and 0 ledger rows created** in the whole window. Nothing to repair.
--
-- WHAT THIS DOES NOT UNDO: migration 050 (the legacy Revolut wallet being
-- ignore-only). That was a deliberate decision, it is still correct, and 050 was
-- written to match either id — so it stays applied and is left alone here.
--
-- Idempotent: re-running finds no API-format ids left and updates 0 rows.

BEGIN;

CREATE TEMP TABLE crosswalk (sheet_id text PRIMARY KEY, api_id text NOT NULL UNIQUE) ON COMMIT DROP;
INSERT INTO crosswalk (sheet_id, api_id) VALUES
    ('OeaD883LY8HbBELgMLNVHZMpkbEPyaHp0opdV', '7991192043957361829'),  -- 360 Performance Savings (5537) (USD), SINGLE via name+currency
    ('j5a1n7R1OmtJ0zekLmMpCg7evP4DrJikqzVpL6', '7814887570436791159'),  -- Black Card (9915) (USD), SINGLE via name+currency
    ('e5a23070-13bb-49af-8f2d-e552e159b570', '8829675791129122371'),  -- Cash Management (USD), SINGLE via name+currency
    ('369564674', '6266063543561075600'),  -- CHASE SAVINGS (USD), CONFIRMED via both
    ('247bc196-4ac8-4bc2-a5ca-69c693a475d3', '4184944067129866862'),  -- Christopher Biedermann (EUR) (2211) (EUR), CONFIRMED via both
    ('d736e5e2-9f13-44da-a96e-b66ad735b8a3', 'acc_01KYS5BECVFH89QPSRQSFN4M99'),  -- Christopher Biedermann (EUR) (8325) (EUR), SINGLE via name+currency
    ('185c3704-14ab-4f1a-8ed0-bd040ce37b85', '3020755806482258456'),  -- Christopher Biedermann (PLN) (5413) (PLN), SINGLE via name+currency
    ('f4f38f9a-199c-4b32-b9f8-074dd0c3febd', 'acc_01KYS5BHZE7F9CJYZHJWXC04ZT'),  -- Christopher Biedermann (PLN) (8325) (PLN), SINGLE via name+currency
    ('06c5dab0-7e8c-40fc-80eb-e2f94dd13ae0', '6521708934254164984'),  -- Christopher Biedermann (USD) (1446) (USD), CONFIRMED via both
    ('4de06156-3a5c-4a12-8701-e28a5ff18d2f', '4044604745776048193'),  -- Christopher Biedermann (USD) (8325) (USD), SINGLE via name+currency
    ('69b7d3c5-fd86-4b6c-929d-073a5ed97704', '9118349300383451158'),  -- CHRISTOPHER F BIEDERMANN (PLN) (1791) (PLN), CONFIRMED via both
    ('1cf189ea-1fc3-44ff-b030-d85093f2825c', '7629175587326935916'),  -- CHRISTOPHER FRANZ BIEDERMANN (EUR) (9421) (EUR), CONFIRMED via both
    ('R1ZQnw7QNqHBJqAxKXEvsZM9pa86e9H99JZv4', '2125222118205134100'),  -- Delta SkyMiles® Reserve Card (1002) (USD), SINGLE via name+currency
    ('e420ad75-9a54-4c3b-b98a-5adbd8b6061e', '238417359251307816'),  -- Fixed Income (USD), SINGLE via name+currency
    ('nEn1jK51zbT4Zq5vA1dPs8E6XomJO6FjjOkdq', '4845293972953545556'),  -- Hilton Honors Aspire Card (1007) (USD), SINGLE via name+currency
    ('190d7bf1-c77d-43bc-9061-b7646669b176', '3434139509958219125'),  -- Individual (USD), SINGLE via name+currency
    ('0331dfa6-706c-415c-aba6-efb81f6fb86d', '3062089709092272539'),  -- Infinity CB (PLN), CONFIRMED via both
    ('ebc00ada-6ee2-43fe-9ed3-df2bf77ecc6c', '306283222131625591'),  -- Infinity KB (PLN), CONFIRMED via both
    ('QD8EXdyENPIqkb5od87AtPYrpvRQOrU993xZw', '2779036839116781874'),  -- Marriott Bonvoy Brilliant® American Express® Card (4003) (USD), SINGLE via name+currency
    ('385966008', '6802282097996095156'),  -- Marriott Chase (USD), CONFIRMED via both
    ('466a4ae8-b682-4256-96aa-e0bcc80de3fb', '4351213228517462827'),  -- OC MEDYCYNY ESTETYCZNEJ (PLN) (8781) (PLN), CONFIRMED via both
    ('3bd9f941-8d06-4302-8950-35b532cebbaa', '1023381748687979037'),  -- Options (USD), SINGLE via name+currency
    ('b235e3d8-34fb-4678-97da-bc03c6f01576', '5739453956153598534'),  -- PKO EUR (EUR), SINGLE via name+currency
    ('6fbf7e12-e099-4d39-ac12-fbf26d81e77d', '2668543056229379631'),  -- PKO Main (PLN), CONFIRMED via both
    ('b2416778-a3a1-44d9-bd34-b62862e97b5b', '5402597747075704143'),  -- PKO OCME (PLN), CONFIRMED via both
    ('012a5d7f-19de-45ee-a451-dfa2481bca47', '193084888964906269'),  -- PKO USD (USD), SINGLE via name+currency
    ('280752349', '4967708320908493007'),  -- Prime Visa (USD), CONFIRMED via both
    ('5216d738-82a9-4956-9b23-aff70d07c827', '8834888811902688614'),  -- Rollover IRA (USD), SINGLE via name+currency
    ('d0bbc717-0e20-4b46-9e50-eb5d323849cc', '6050344781753535419'),  -- SAVINGS (PLN) (2790) (PLN), CONFIRMED via both
    ('4edb12ab-749d-4e1f-bbe4-5d31aaee30d8', '2836626511221389035'),  -- Stocks (USD), SINGLE via name+currency
    ('4741523', '7537429121392136946')  -- TOTAL CHECKING (USD), CONFIRMED via both
;

-- Reversing must not collide either: a Sheet id already present would mean two
-- accounts merging on the way back.
DO $$
DECLARE collide INT;
BEGIN
  SELECT COUNT(*) INTO collide
    FROM crosswalk c
   WHERE EXISTS (SELECT 1 FROM account_source_mappings m WHERE m.source='bank-feed' AND m.external_name = c.sheet_id)
     AND EXISTS (SELECT 1 FROM account_source_mappings o WHERE o.source='bank-feed' AND o.external_name = c.api_id);
  IF collide > 0 THEN
    RAISE EXCEPTION 'migration 051: % id(s) present in BOTH directions — cannot reverse safely', collide;
  END IF;
END $$;

UPDATE account_source_mappings m
   SET external_name = c.sheet_id
  FROM crosswalk c
 WHERE m.source = 'bank-feed' AND m.external_name = c.api_id;

UPDATE bankfeed_staging s
   SET feed_account_external_id = c.sheet_id
  FROM crosswalk c
 WHERE s.feed_account_external_id = c.api_id;

-- The post-condition that actually proves the rollback worked is not a count of
-- rows changed — it is that the reconcile page can join again. Assert exactly
-- that: every live mapping must once more resolve to a feed balance.
DO $$
DECLARE orphan_stage INT; no_balance INT;
BEGIN
  SELECT COUNT(*) INTO orphan_stage
    FROM bankfeed_staging s
   WHERE NOT EXISTS (
     SELECT 1 FROM account_source_mappings m
      WHERE m.source = 'bank-feed' AND m.external_name = s.feed_account_external_id);
  IF orphan_stage > 0 THEN
    RAISE EXCEPTION 'migration 051: % staged row(s) still resolve to no mapping', orphan_stage;
  END IF;

  SELECT COUNT(*) INTO no_balance
    FROM account_source_mappings m
   WHERE m.source = 'bank-feed' AND m.ignored IS NOT TRUE AND m.account_id IS NOT NULL
     AND NOT EXISTS (
       SELECT 1 FROM bankfeed_balances b WHERE b.feed_account_external_id = m.external_name);
  IF no_balance > 0 THEN
    RAISE EXCEPTION 'migration 051: % live mapping(s) still have no feed balance', no_balance;
  END IF;
END $$;

COMMIT;
